# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Navicli < Formula
  desc "A lightweight command line music player for Navidrome"
  homepage "https://github.com/yhkl-dev/NaviCLI"
  version "2.2.3"
  license "MIT"

  depends_on "mpv"
  depends_on :macos

  if Hardware::CPU.arm?
    url "https://github.com/yhkl-dev/NaviCLI/releases/download/v2.2.3/release.tar.gz"
    sha256 "c2a685600f735b099cfb4f0e59ba46495da0373bdc72706f30428af9d962e17a"

    define_method(:install) do
      bin.install "navicli"
    end
  end

  test do
    assert_predicate bin/"navicli", :exist?
  end
end
